### PR TITLE
Update getopq.sh

### PR DESCRIPTION
**Pull request by Tribunny**
add proxy for download application.

### CODE REVIEW

**Comment by ZegWe** [comment]
docker image are auto generated and pushed to DockerHub repository by Github Action, so there is no need to use a github proxy.

**Comment by Tribunny** [comment]
目录映射可以给参考一下嘛

**Comment by ZegWe** [comment]
As writen in [Dockerfile](https://github.com/ZegWe/opq-docker/blob/4fa2921e8bf8c368ec116843379ed3b67a5d4646/Dockerfile#L11), work directory is `/home/OPQBot`, so you should map your subdirectories or files in to it.
Such as `-v $(pwd)/xxx:/home/OPQBot/xxx`.

**Comment by Tribunny** [comment]
okay

**Comment by Tribunny** [comment]
something get wrong，docker container Exited 2

**Comment by Tribunny** [comment]
I used this command `docker run -itd --name opq -p 7268:8888 -e GITTER_TOKEN="be60d507259f25be2580b62be7f647ee7ad48d30" -v /opq:/home/OPQBot  zegwe/opqbot` to create container.

**Comment by ZegWe** [comment]
`/home/OPQBot` is work directory, and all the user files are in it. So you should map a subdirectory instead of the whole work directory itself.

**Pull request closed without merging**
